FROM docker.elastic.co/logstash/logstash:6.2.3
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
RUN rm -f /usr/share/logstash/config/logstash.yml
ADD logstash.conf /usr/share/logstash/pipeline/logstash.conf
ADD logstash.yml /usr/share/logstash/config/logstash.yml
RUN bin/logstash-plugin install logstash-input-exec
RUN bin/logstash-plugin install logstash-output-syslog
